//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Animator.rc
//
#define IDS_DIALOGFAILURE               1
#define IDS_STRUCTSIZE                  2
#define IDS_INITIALIZATION              3
#define IDNEXT                          3
#define IDSETMIN                        3
#define IDS_NOTEMPLATE                  4
#define IDRENAME                        4
#define IDPREV                          4
#define IDSETMAX                        4
#define IDS_NOHINSTANCE                 5
#define IDDEL                           5
#define IDROL                           5
#define IDS_LOADSTRFAILURE              6
#define IDDLINK                         6
#define IDZOOM                          6
#define IDS_FINDRESFAILURE              7
#define IDUNLINK                        7
#define IDFULLMAP                       7
#define IDS_LOADRESFAILURE              8
#define IDS_LOCKRESFAILURE              9
#define IDS_MEMALLOCFAILURE             10
#define IDS_MEMLOCKFAILURE              11
#define IDS_NOHOOK                      12
#define IDS_SETUPFAILURE                13
#define IDS_PARSEFAILURE                14
#define IDS_RETDEFFAILURE               15
#define IDS_LOADDRVFAILURE              16
#define IDS_GETDEVMODEFAIL              17
#define IDS_INITFAILURE                 18
#define IDS_NODEVICES                   19
#define IDS_NODEFAULTPRN                20
#define IDS_DNDMMISMATCH                21
#define IDS_CREATEICFAILURE             22
#define IDS_PRINTERNOTFOUND             23
#define IDS_NOFONTS                     24
#define IDS_SUBCLASSFAILURE             25
#define IDS_INVALIDFILENAME             26
#define IDS_BUFFERTOOSMALL              27
#define IDS_FILTERSTRING                28
#define IDS_UNKNOWNERROR                29
#define IDD_COMDLG32                    100
#define IDE_PATH                        102
#define IDM_FILEOPEN                    106
#define IDM_EXIT                        107
#define IDM_ABOUT                       108
#define IDM_NEW                         109
#define IDM_SAVE                        110
#define IDM_SAVEAS                      111
#define IDM_JOIN                        112
#define IDD_ABOUT                       113
#define IDM_LOADTEX                     114
#define IDM_SAVECONTOUR                 115
#define ID_OBJECTS_CREATE               117
#define IDM_STATISTIC                   120
#define IDD_CAMERA                      120
#define IDM_INFO                        120
#define IDM_IMPTEX                      121
#define IDM_SAVETEX                     122
#define IDD_OLIST                       122
#define MENU_SAVETEXTURE                122
#define ID_OBJECTS_RENAMEOBJECT         123
#define ID_OBJECTS_LINKOBJECTTO         124
#define ID_OBJECTS_UNLINKOBJECT         125
#define ID_OBJECTS_SHOWLINKSTREE        126
#define IDM_SHOWOLIST                   126
#define IDD_RENAMEOBJ                   126
#define ID_OBJECTS_SHOWALLOBJECTS       127
#define IDI_ICON1                       127
#define IDD_OTREE                       127
#define ID_COMMANDS_SHOWTEXTURE         128
#define IDM_VIEWTEXTURE                 128
#define IDM_LOADTEX2                    129
#define IDD_EMODE                       129
#define IDM_JOINTEX                     129
#define IDM_ZOOM                        130
#define IDM_ZOOMIN                      132
#define IDM_ZOOMOUT                     133
#define IDD_INFO                        133
#define IDM_SETSAME                     134
#define IDD_FLAGS                       134
#define FaceFlagsDB                     134
#define IDC_HAND                        136
#define IDM_WMODE                       137
#define IDC_SQUARE                      137
#define IDM_ANI                         138
#define IDB_POINT                       138
#define IDM_ZERO                        140
#define IDC_MOVEMODE1                   142
#define IDM_EDITMAP                     143
#define IDC_MOVEMODE2                   143
#define IDM_ASFLAGS                     144
#define IDC_MOVEMODE3                   144
#define IDM_ASFLAGSO                    145
#define IDM_AUTOMAP                     146
#define ShowObjectDB                    147
#define IDM_UNDO                        148
#define IDC_3DSCALE                     149
#define MENU_GENERATE_CUBE              149
#define SaveContourDB                   150
#define MENU_GENERATE_SPHERE            150
#define MENU_GENERATE_CYLINDER          151
#define MENU_GENERATE_CIRCLE            152
#define MENU_CREATEGROUP                155
#define IDD_PROPERTIES                  156
#define AutomapDB                       157
#define MENU_REMOVE                     157
#define IDC_EMPTY                       158
#define MENU_COPY                       159
#define IDB_PAINTTOOLBAR                162
#define IDC_ZOOMIN                      163
#define MENU_DELSELECTION               163
#define IDC_ZOOMOUT                     164
#define MENU_MARKUSED                   164
#define IDC_PIXEL                       165
#define MENU_CLEARMAPPING               165
#define CubeParamsDB                    166
#define MENU_MOVEMAPPING                166
#define MENU_MOVETEXTURE                166
#define SphereParamsDB                  167
#define MENU_CLEARTEXTURE               167
#define CylinderParamsDB                168
#define MENU_OPTIONS                    168
#define CircleParamsDB                  169
#define MENU_LEAVEVERTECES              169
#define MENU_MARKUNGROUPPED             170
#define SaveObjectContourDB             171
#define MENU_SELECTALL                  171
#define PlaceObjectDB                   172
#define IDC_EDITMAP                     172
#define MapWndDB                        173
#define GroupNameDB                     174
#define IDM_SAVEANI                     174
#define IDM_OPENTRACK                   175
#define ID_EDIT_UNDO                    176
#define ID_EDIT_MIRRORKEYS              178
#define IDM_MIRRORTRACK                 178
#define IDM_REVERSETRACK                178
#define ID_EDIT_PROPERTIES              180
#define IDM_PLAYANI                     181
#define IDM_OPENNEXT                    182
#define IDM_PLAYREAL                    183
#define IDM_MIRRORKEY                   184
#define IDM_OLIST                       185
#define IDM_SHOWSCEL                    186
#define IDM_SHOWMODEL                   187
#define IDM_ROLLTRACK                   188
#define ID_EDIT_RLPROP                  189
#define ID_SAVEMAP                      190
#define OptionsDB                       191
#define ID_RESTOREMAP                   191
#define IDM_INVERTTRACK                 192
#define MoveTextureDB                   193
#define IDM_SHOWMODELT                  193
#define IDD_APROP                       194
#define IDM_SetPhysic                   194
#define IDD_ROLL                        196
#define IDM_APPLYF                      196
#define IDD_RLPARAMS                    197
#define IDM_StartPhysic                 197
#define IDM_EndPhysic                   198
#define IDD_SETMATRIX                   199
#define IDM_SAVEIKAS                    199
#define IDD_SETPHYSIC                   200
#define IDM_OpenIK                      200
#define IDM_SHOWSPHERES                 201
#define IDD_SETPHYS                     202
#define ID_IK_SETAUTOSPHERESSHIFTR      202
#define IDM_SETAUTOSPHERER              203
#define ID_TRACKBMP                     204
#define IDD_TRACKBMP                    205
#define ID_SYNCHRO                      206
#define IDD_IKPROP                      206
#define IDM_SHOWBACK                    207
#define ID_IKPROP                       208
#define ID_CALCANGELS                   209
#define ID_OBJSMOOTH                    212
#define ID_OBJSMOOTHALL                 213
#define IDM_SAVE3DF                     214
#define ID_RECALCALLANGLES              215
#define IDE_SELECTED                    1022
#define IDC_MODE1                       1027
#define IDC_MODE2                       1028
#define IDC_MODE3                       1029
#define IDC_MODE4                       1030
#define IDC_COLOR                       1033
#define IDC_COLOR1                      1036
#define IDC_COLOR2                      1037
#define IDC_COLOR3                      1038
#define IDC_COLOR4                      1039
#define IDC_CENTER                      1044
#define IDC_POINT                       1045
#define IDC_LIST                        1046
#define IDC_SHOWOBJ                     1046
#define IDC_ZBUF                        1046
#define IDC_CENTER2                     1047
#define IDC_CENTER_4CAMERA              1047
#define IDC_POINT2                      1048
#define IDC_POINT_4CAMERA               1048
#define IDC_SHOWOBJ2                    1049
#define IDC_SHOWOBJ_4CAMERA             1049
#define IDC_EDIT1                       1056
#define IDC_EDIT                        1056
#define IDC_SCALE                       1056
#define IDC_CUBEEDGE                    1056
#define IDC_VERTICES                    1056
#define IDC_POINTS                      1056
#define IDC_FILENAME                    1056
#define IDC_COORD1                      1056
#define IDC_LAYER                       1057
#define IDC_EDIT2                       1057
#define IDC_TREE1                       1058
#define IDC_TREE                        1058
#define IDC_TREEO                       1058
#define IDC_EDIT3                       1058
#define IDLINK                          1059
#define IDC_EDIT4                       1059
#define IDC_EDITK1                      1060
#define IDC_EDIT5                       1060
#define IDC_GRIDLINES                   1061
#define IDC_EDITK2                      1061
#define IDC_COMBO                       1067
#define IDC_MOUSE                       1068
#define IDC_ALLWIN                      1069
#define IDC_SLIDER                      1070
#define IDC_MAP                         1074
#define IDC_VSCROLL                     1076
#define IDC_HSCROLL                     1078
#define IDC_OCNT                        1079
#define IDC_FCNT                        1080
#define IDC_VCNT                        1081
#define IDC_TINFO                       1082
#define IDC_ST                          1085
#define IDC_DSIDE                       1086
#define IDC_DOUBLESIDE                  1086
#define IDC_OPAC                        1087
#define IDC_OPACITY                     1087
#define IDC_TRANS                       1088
#define IDC_TRANSPARENT                 1088
#define IDC_FNAME                       1090
#define IDC_VINFO                       1091
#define IDC_RADIO1                      1091
#define IDC_MINFO                       1092
#define IDC_RADIO2                      1092
#define ID_CLOSE                        1092
#define ID_SHOWALL                      1093
#define ID_SHOW                         1094
#define IDC_HIDDENOBJLIST               1095
#define IDC_CONTOUR                     1096
#define IDC_ANGLE                       1097
#define IDC_SAVE                        1098
#define IDC_CLOSE                       1099
#define IDC_XOFFSET                     1102
#define IDC_YOFFSET                     1103
#define IDC_CENTER_4USER                1104
#define IDC_XOFFSET2                    1104
#define IDC_POINT_4USER                 1105
#define IDC_YOFFSET2                    1105
#define IDC_AUTOMAP                     1106
#define IDC_XOFFSET3                    1106
#define IDC_YOFFSET3                    1107
#define IDC_SCALETEXT                   1108
#define IDC_XOFFSET4                    1108
#define IDC_ANGLETEXT                   1109
#define IDC_YOFFSET4                    1109
#define IDC_GROUP1                      1111
#define IDC_GROUP2                      1112
#define IDC_TEXT                        1113
#define IDC_AUTOMAPTEXT                 1114
#define IDC_AUTOMAPINFO                 1116
#define IDC_START                       1121
#define IDC_TRIANGLE                    1124
#define IDC_HEMISPHERE                  1128
#define IDC_BOTTOM                      1129
#define IDC_RADIUS                      1130
#define IDC_TOP                         1132
#define IDC_LAYERSCROLL                 1133
#define IDC_SCROLLBAR                   1134
#define IDC_X                           1135
#define IDC_Y                           1136
#define IDC_DX                          1137
#define IDC_DY                          1138
#define IDC_REAL                        1139
#define IDC_REAL2                       1140
#define IDC_REAL3                       1141
#define IDC_REAL4                       1142
#define IDC_WIDTH                       1143
#define IDC_HEIGHT                      1144
#define IDC_Z                           1148
#define IDC_FIT                         1154
#define IDC_MIRROR                      1155
#define IDC_FIT2                        1155
#define IDC_POINTSCROLL                 1156
#define IDC_COVERING                    1157
#define IDC_FIT3                        1158
#define IDC_FIT4                        1159
#define IDC_TEXHEIGHT                   1162
#define IDC_CHECK2                      1163
#define IDC_TEXHEIGHT2                  1163
#define IDC_MOVELINKS                   1163
#define IDC_CHECK3                      1164
#define IDC_TEXHEIGHT3                  1164
#define IDC_ROTATELINKS                 1164
#define IDC_CHECKFORCE                  1164
#define IDC_TEXWIDTH                    1165
#define IDC_ACTIVEX                     1165
#define IDC_TEXWIDTH2                   1166
#define IDC_ACTIVEY                     1166
#define IDC_TEXWIDTH3                   1167
#define IDC_ACTIVEZ                     1167
#define IDC_TEXWIDTH4                   1168
#define IDC_CHECKFORCE2                 1168
#define IDC_CHECKFIX                    1168
#define IDC_TEXHEIGHT4                  1169
#define IDC_CONTOURS                    1172
#define IDC_BROWSE                      1182
#define IDC_COMMENT                     1183
#define IDC_TEXTURE                     1185
#define IDC_BUTTON1                     1186
#define IDUPDATEFIX                     1186
#define IDC_BUTTON2                     1187
#define IDC_BUTTON3                     1188
#define IDC_BUTTON4                     1189
#define IDC_BUTTON5                     1190
#define IDC_BUTTON6                     1191
#define IDC_BUTTON7                     1192
#define IDC_BUTTON8                     1193
#define IDC_COORD2                      1194
#define IDC_COORD3                      1195
#define IDC_COORD4                      1196
#define IDC_COORD5                      1197
#define IDC_COORD6                      1198
#define IDC_COORD7                      1199
#define IDC_COORD8                      1200
#define IDB_ROTATE                      1201
#define IDB_SCALE                       1202
#define IDB_MOVE                        1203
#define IDC_ALPHA                       1204
#define IDC_BETHA                       1205
#define IDC_BEEP                        1208
#define IDC_COPYLINKS                   1210
#define IDC_SCALELINKS                  1211
#define IDC_MIRRORLINKS                 1212
#define IDC_MAPPING                     1220
#define IDC_NOCONTOUR                   1221
#define IDB_SCALEHOR                    1222
#define IDB_SCALEVERT                   1223
#define IDC_DARKBACK                    1224
#define IDC_AUTOSAVE                    1225
#define IDC_SCALECOEFF                  1231
#define IDC_HIDELINKS                   1232
#define IDC_SELECT                      1234
#define IDC_ROTATE                      1235
#define IDC_MOVE                        1236
#define IDC_SHOWMAPPING                 1239
#define IDC_REVVIEW                     1243
#define IDC_MIN1                        1244
#define IDC_MIN2                        1245
#define IDC_MIN3                        1246
#define IDC_MAX1                        1247
#define IDC_MAX2                        1248
#define IDC_MAX3                        1249
#define IDC_CHECKBASE                   1250
#define IDC_EDITMASS                    1251
#define IDC_WABS                        1252
#define IDC_EDITG                       1253
#define IDC_FABS                        1253
#define IDC_EDITWINDPOWER               1254
#define IDC_FX                          1254
#define IDC_FY                          1255
#define IDC_EDITWINDX                   1256
#define IDC_FZ                          1256
#define IDC_EDITWINDY                   1257
#define IDC_CURX                        1257
#define IDC_EDITWINDZ                   1258
#define IDC_CURY                        1258
#define IDC_EDITDUMP                    1259
#define IDC_CURZ                        1259
#define IDC_EDITTIME                    1260
#define IDC_RESTRICTX                   1260
#define IDC_RESTRICTY                   1261
#define IDC_CHECK1                      1261
#define IDC_RESTRICTZ                   1262
#define IDC_WABS2                       1263
#define IDC_FABS2                       1264
#define IDM_WAV                         2000
#define IDM_PLAYSOUND                   2001
#define IDM_WAV_UPDATE                  2002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         216
#define _APS_NEXT_CONTROL_VALUE         1262
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
